### ISSUE TITLE
"20200302 2.4.5. missing library Decrypt.pm"

### ISSUE THREAD

**Issue by Ranzo3** [delphix/dxtoolkit#126]
** Expected Behavior**
dx_config --help produces help test

** Actual Behavior**
anzoTaylorsMBP:dxtoolkit2 ranzo.taylor$ ./dx_config --help
Can't load '/var/folders/w9/5pc6krks45x17lm2jn0rr0bw0000gn/T/par-72616e7a6f2e7461796c6f72/cache-d60f855584a2f02c758fbbbce44e9800f8454f26/79b0b4ca.bundle' for module Filter::Crypto::Decrypt: dlopen(/var/folders/w9/5pc6krks45x17lm2jn0rr0bw0000gn/T/par-72616e7a6f2e7461796c6f72/cache-d60f855584a2f02c758fbbbce44e9800f8454f26/79b0b4ca.bundle, 1): Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /var/folders/w9/5pc6krks45x17lm2jn0rr0bw0000gn/T//par-72616e7a6f2e7461796c6f72/cache-d60f855584a2f02c758fbbbce44e9800f8454f26/79b0b4ca.bundle
  Reason: image not found at /usr/local/Cellar/perl/5.30.1/lib/perl5/5.30.1/darwin-thread-multi-2level/DynaLoader.pm line 197.
 at /usr/local/Cellar/perl/5.30.1/lib/perl5/site_perl/5.30.1/PAR/Heavy.pm line 140.
BEGIN failed--compilation aborted at Filter/Crypto/Decrypt.pm line 39.
Compilation failed in require at /var/folders/w9/5pc6krks45x17lm2jn0rr0bw0000gn/T/par-72616e7a6f2e7461796c6f72/cache-d60f855584a2f02c758fbbbce44e9800f8454f26/inc/lib/dbutils.pm line 1.
BEGIN failed--compilation aborted at /var/folders/w9/5pc6krks45x17lm2jn0rr0bw0000gn/T/par-72616e7a6f2e7461796c6f72/cache-d60f855584a2f02c758fbbbce44e9800f8454f26/inc/lib/dbutils.pm line 1.
Compilation failed in require at Engine.pm line 56.
BEGIN failed--compilation aborted at Engine.pm line 56.
Compilation failed in require at script/dx_config.pl line 37.
BEGIN failed--compilation aborted at script/dx_config.pl line 37.

**Steps To Reproduce the Problem**
Downloaded 2.4.5 onto my Mac
Ran install.sh
Attempted dx_config

**Screenshots**

**Version**
2.4.5

**Comment by Ranzo3** [comment]
Same machine works on 2.4.2 which also uses install.sh approach

**Comment by pioro** [comment]
Hey Ranzo,

New build was done using a Github Actions and OSX provided by it.
Let me working on the build process fixture.

Marcin

**Comment by pioro** [comment]
Fixed in latest build - 2.4.6.1
